### ISSUE TITLE
Save and reuse preset tag feature doen't work with Cinema 4D R25 

### ISSUE THREAD

**Issue by YaooYingg** [pnmocap/neuron_mocap_live-c4d#1]
Neuron Mocap Live-C4D version：v1.0.0 beta
Reproduce steps:
1. Import a character model into C4D
2. Add a Neuron Mocap Live tag to the character model 
2. Finish joints map 
3. Save the Preset 
4. Select the preset I just saved to apply it to another character model
Result: Jonts map is empty

**Comment by snow-boy** [comment]
already fixed
